nelmio_api_doc:
  documentation:
    info:
      title: My App
      description: This is an awesome app!
      version: 1.0.0

    components:
      schemas:
        rented_info:
          properties:
            date:
              type: string
              format: date
            stations:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  rented_items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string

        general_error:
          title: "General error"
          description: "General exception"
          type: object
          properties:
            code:
              type: integer
              readOnly: true
            message:
              type: string
              readOnly: true
        validation_error:
          title: "Validation errors"
          description: "Validation errors"
          type: object
          properties:
            code:
              type: integer
              readOnly: true
            errors:
              type: array
              items:
                type: string

      responses:
        GeneralError:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/general_error"
        Unauthorized:
          description: Unauthorized access
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/general_error"
        NotFound:
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/general_error"
        ValidationError:
          description: Request parameters are invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/validation_error"

  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
